### ISSUE TITLE
Remove Gban and Gmute

### ISSUE THREAD

**Issue by Netkas** [intellivoid/HarukaAya#1]
It's time to remove these two outdated features because they serve no purpose in terms of combating spam, if this feature is needed to prevent specific users from using the bot then another feature needs to be implemented other than gbanning. The reason why these features aren't needed anymore is because combating spam can be done with third party and trustworthy services such as SpamWatch and SpamProtectionBot by implementing their API into the project.

**Comment by zakaryan2004** [comment]
Done in ebf0071
