### ISSUE TITLE
[slaps] Remind users not to slap Haruka Aya, else get temp-muted for a minute

### ISSUE THREAD

**Issue by Netkas** [intellivoid/HarukaAya#4]
I would like to recommend to temp-mute people who slap Haruka Aya. Before they get temp-muted, they'll get scolded first.

For admins, this makes bot devs more triggered because the bot can't mute the admins. Instead, scold them.

[https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2](https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2)

**Comment by Netkas** [comment]
or just check if the id that is being slapped is bot's or not and reply with "I'm not doing that to myself!" then return... simple right?

[https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2#note_404342863](https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2#note_404342863)

**Comment by Netkas** [comment]
> or just check if the id that is being slapped is bot's or not and reply with "I'm not doing that to myself!" then return... simple right?
> 
> https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2#note_404342863

Agreed to your feedback.
[https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2#note_404481791](https://gitlab.com/HarukaNetwork/OSS/HarukaAya/-/issues/2#note_404481791)

**Comment by Netkas** [comment]
# Notice

This issue has been moved form GitLab

**Comment by zakaryan2004** [comment]
This seems to be an unnecessary and annoying addition to the already unnecessary memes. It's additional effort with no benefit whatsoever.

**Comment by Netkas** [comment]
> This seems to be an unnecessary and annoying addition to the already unnecessary memes. It's additional effort with no benefit whatsoever.

I have to agree with this, it provides no additional benefits. Closing the issue.
